### ISSUE TITLE
Bug on selecting category while adding new peer

### ISSUE THREAD

**Issue by eserdinyo** [okandavut/find-superpeer#18]
When you try to add a new peer if you select a category from the label it only affects the first item.

**Comment by eserdinyo** [comment]
I didn't look at the issues. Same here #7 :)

**Comment by okandavut** [comment]
Do  you have same problem right now? @eserdinyo

**Comment by eserdinyo** [comment]
Yes. Still have the same problem.

**Comment by okandavut** [comment]
@eserdinyo are you working on this issue?

**Comment by eserdinyo** [comment]
No.

**Comment by okandavut** [comment]
Problem was solved can you check is it ok? @eserdinyo

**Comment by eserdinyo** [comment]
Okay. It works as expected. There is no problem anymore ✌️

**Comment by okandavut** [comment]
Thanks for your effort! 💯
