### ISSUE TITLE
Ana sayfa gösterilen kayıt sayısı

### ISSUE THREAD

**Issue by yisleyen** [okandavut/find-superpeer#29]
Ana sayfada yer sayfada gösterilecek kayıt sayısının yer aldığı bölüm sayfa numaralarından büyük görünüyor. Css tarafında display: inline-flex kaldırıldığında sayfa numaraları ile aynı boyutlarda duruyor.

**Comment by okandavut** [comment]
Problem solved thanks for your effort to report an issue! :)
